services:
  # Create config files from .env on startup
  consul-config:
    image: alpine:latest
    container_name: consul-config-init
    volumes:
      - ./consul/scripts:/scripts
      - ./consul/config:/config
      - ./.env:/.env
    command: >
      sh -c "
        apk add --no-cache jq bash dos2unix &&
        cd /scripts &&
        dos2unix generate-consul-config.sh &&
        chmod +x generate-consul-config.sh &&
        bash ./generate-consul-config.sh
      "
    networks:
      - consul-net
      
  # Create Traefik config files from .env on startup
  traefik-config:
    image: alpine:latest
    container_name: traefik-config-init
    volumes:
      - ./traefik/scripts:/scripts
      - ./traefik/config:/config
      - ./.env:/.env
    command: >
      sh -c "
        apk add --no-cache jq bash dos2unix &&
        cd /scripts &&
        dos2unix generate-traefik-config.sh &&
        chmod +x generate-traefik-config.sh &&
        bash ./generate-traefik-config.sh
      "
    networks:
      - consul-net

  # Consul server
  consul-server:
    image: hashicorp/consul:1.15.4
    container_name: consul-server
    restart: unless-stopped
    depends_on:
      - consul-config
    volumes:
      - consul-data:/consul/data
      - ./consul/config:/consul/config
    ports:
      - "${CONSUL_HTTP_PORT}:8500"
      - "${CONSUL_DNS_PORT}:8600/tcp"
      - "${CONSUL_DNS_PORT}:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_AGENT_LEVEL=${CONSUL_LOG_LEVEL}
    command: "agent -server -ui -node=consul-server -bootstrap-expect=1 -client=0.0.0.0 -config-dir=/consul/config"
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - consul-net

  # Traefik API Gateway
  traefik:
    image: traefik:3.3
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - consul-server
      - traefik-config
      - traefik-consul-register
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - ./traefik/config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--configFile=/etc/traefik/traefik.yaml"
    networks:
      - consul-net
      - traefik-net
      
  # Register Traefik configuration in Consul
  traefik-consul-register:
    image: alpine:latest
    container_name: traefik-consul-register
    depends_on:
      - consul-server
      - traefik-config
    volumes:
      - ./traefik/scripts:/scripts
      - ./traefik/config:/config
    command: >
      sh -c "
        apk add --no-cache curl jq bash dos2unix &&
        cd /scripts &&
        dos2unix register-traefik-config-to-consul.sh &&
        chmod +x register-traefik-config-to-consul.sh &&
        bash ./register-traefik-config-to-consul.sh
      "
    networks:
      - consul-net

  vault:
    image: hashicorp/vault:1.19
    container_name: vault
    restart: unless-stopped
    depends_on:
      - consul-server
    ports:
      - "${VAULT_PORT:-8200}:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
    command: server -config=/vault/config/vault.hcl
    networks:
      - consul-net

  # Vault initialization container
  vault-init:
    image: hashicorp/vault:1.19
    container_name: vault-init
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:${VAULT_PORT}
      # Pass through all environment variables
      - CONSUL_SERVER=${CONSUL_SERVER:-consul-server}
      - CONSUL_HTTP_PORT=${CONSUL_HTTP_PORT:-8500}
      - VAULT_CONSUL_PATH=${VAULT_CONSUL_PATH:-vault/}
      - VAULT_PORT=${VAULT_PORT:-8200}
      - VAULT_TLS_DISABLE=${VAULT_TLS_DISABLE:-1}
      - VAULT_UI_ENABLED=${VAULT_UI_ENABLED:-true}
      - VAULT_DISABLE_MLOCK=${VAULT_DISABLE_MLOCK:-true}
      - VAULT_API_ADDR=${VAULT_API_ADDR:-0.0.0.0}
      # Secrets to store in Vault
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DB_PASSWORD=${DB_PASSWORD}
      # Other configs
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID:-root}
    volumes:
      - ./vault/scripts:/scripts
      - ./vault/config:/vault/config
      - ./.env:/.env
    command: >
      sh -c "
        apk add --no-cache jq bash dos2unix &&
        cd /scripts &&
        dos2unix init-vault.sh &&
        chmod +x init-vault.sh &&
        bash ./init-vault.sh
      "
    networks:
      - consul-net

networks:
  consul-net:
    driver: bridge
  traefik-net:
    driver: bridge

volumes:
  consul-data:
