services:
  # Create config files from .env on startup
  consul-config:
    image: alpine:latest
    container_name: consul-config-init
    volumes:
      - ./consul/scripts:/scripts
      - ./consul/config:/config
      - ./.env:/.env
    command: >
      sh -c "
        apk add --no-cache jq bash dos2unix &&
        cd /scripts &&
        dos2unix generate-consul-config.sh &&
        chmod +x generate-consul-config.sh &&
        bash ./generate-consul-config.sh
      "
    networks:
      - consul-net

  # Consul server
  consul-server:
    image: hashicorp/consul:${CONSUL_VERSION}
    container_name: consul-server
    restart: unless-stopped
    depends_on:
      - consul-config
    volumes:
      - consul-data:/consul/data
      - ./consul/config:/consul/config
    ports:
      - "${CONSUL_HTTP_PORT}:8500"
      - "${CONSUL_DNS_PORT}:8600/tcp"
      - "${CONSUL_DNS_PORT}:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_AGENT_LEVEL=${CONSUL_LOG_LEVEL}
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -config-dir=/consul/config"
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - consul-net

networks:
  consul-net:
    driver: bridge

volumes:
  consul-data:
