# Dynamic configuration (will be stored in Consul)
http:
  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
    
    secure-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
    
    compress:
      compress:
        excludedContentTypes:
          - "text/event-stream"
    
    basic-auth:
      basicAuth:
        users:
          - "admin:adminpassword"
