## Static configuration for Traefik v3
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  
  consul:
    endpoints:
      - "http://consul-server:8500"
    rootKey: "traefik"

log:
  level: "INFO"
