http:
  middlewares:
    # Rate limiting middleware
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m
    
    # CORS configuration
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "https://example.com"
          - "https://*.example.com"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
        accessControlMaxAge: 100
        accessControlAllowCredentials: true
        addVaryHeader: true
    
    # JWT Authentication middleware
    jwt-auth:
      forwardAuth:
        address: "http://auth-service:8080/validate"
        authResponseHeaders:
          - "X-User-ID"
          - "X-User-Role"
    
    # Basic security headers
    security-headers:
      headers:
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Content-Security-Policy: "default-src 'self'"
          Referrer-Policy: "strict-origin-when-cross-origin"
        
    # Retry middleware
    retry-middleware:
      retry:
        attempts: 3
        initialInterval: "100ms"
        
    # Circuit breaker
    circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.10 || ResponseCodeRatio(500, 600, 0, 600) > 0.25"
