name: Sync Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for history
          path: source-code

      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync wiki content
        run: |
          # Remove all files from wiki (except .git folder)
          find wiki -mindepth 1 -name ".git" -prune -o -exec rm -rf {} \; 2> /dev/null || true
          
          # Copy all files from docs folder
          cp -r source-code/docs/* wiki/
          
          # Convert Home.md to _Sidebar.md for navigation
          if [ -f "wiki/Home.md" ]; then
            # Extract links from Home.md and create sidebar
            grep -E "\[.*\]\(.*\)" wiki/Home.md | sed 's/^- //' > wiki/_Sidebar.md
          fi
          
          cd wiki
          
          # Check if there are changes
          if git status --porcelain | grep .; then
            git config user.name "GitHub Actions"
            git config user.email "github-actions@github.com"
            git add .
            git commit -m "Sync wiki from docs folder"
            git push
            echo "Wiki has been updated"
          else
            echo "No changes detected"
          fi
